test 3

diff --git a/.github/workflows/artifact_gke.yml b/.github/workflows/artifact_gke.yml
--- a/.github/workflows/artifact_gke.yml
+++ b/.github/workflows/artifact_gke.yml
@@ -32,6 +32,16 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
+    - name: Debug Secrets
+      run: |
+        if [[ -z "${{ secrets.GKE_SA_KEY }}" ]]; then
+          echo "GKE_SA_KEY is missing or empty!"
+          exit 1
+        else
+          echo "GKE_SA_KEY is present!"
+          echo '${{ secrets.GKE_SA_KEY }}' | jq . || echo "Invalid JSON format!"
+        fi
+
     # Setup gcloud CLI
     - id: 'auth'
       uses: 'google-github-actions/auth@v2'
